# suppress inspection "UnusedProperty" for whole file
server:
  port: 8090
# emulator has different port, this is default livereload port
spring:
  devtools:
    livereload:
      port=35729
websocket:
  uri=ws://localhost:8091/hwAPI

# OpenApi
springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /api-docs